# Generated by Django 5.0 on 2023-12-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_client_address_alter_client_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile_picture',
            new_name='client_avatar',
        ),
    ]
