# Generated by Django 5.0 on 2023-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_client_client_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default='00000', max_length=30),
        ),
    ]
