# Generated by Django 5.0 on 2023-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_client_address_alter_client_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='...', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default='...', max_length=30),
        ),
    ]
