# Generated by Django 5.0 on 2023-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_client_address_alter_client_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='...', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='(xxx)xxx-xxxx', max_length=50),
        ),
    ]
