# Generated by Django 5.0 on 2023-12-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(blank=True, default='(xxx)xxx-xxxx', null=True),
        ),
    ]
