# Generated by Django 5.0 on 2023-12-30 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_client_phone_number'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('project_name', models.CharField(max_length=255)),
                ('project_duration', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('invoice_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=200)),
                ('payment_date', models.DateField(max_length=200, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GHC', 'GHC')], max_length=200)),
                ('item_title', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('client_note', models.TextField(max_length=100000)),
                ('updated_time_stamp', models.DateTimeField(auto_now=True)),
                ('created_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client', to_field='name')),
            ],
            options={
                'ordering': ['-updated_time_stamp'],
            },
        ),
    ]
