# Generated by Django 5.0 on 2023-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_client_name_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_note',
            field=models.TextField(),
        ),
    ]
