# Generated by Django 5.0 on 2023-12-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoice_client_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_note',
            field=models.TextField(max_length=100000),
        ),
    ]
