# Generated by Django 5.0 on 2024-01-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_invoice_client_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='invoice.client', to_field='name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client', to_field='email'),
        ),
    ]
