# Generated by Django 5.0 on 2024-01-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_invoice_client_name_alter_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.client', to_field='email'),
        ),
    ]
