# Generated by Django 5.0 on 2024-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_invoice_client_name_alter_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
