# Generated by Django 5.0 on 2024-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
    ]
