# Generated by Django 5.0 on 2024-01-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
