# Generated by Django 5.0 on 2024-01-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.ForeignKey(help_text='Select a client for this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.client', to_field='name'),
        ),
    ]
