# Generated by Django 5.0 on 2024-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
