# Generated by Django 5.0 on 2024-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GHC', 'GHC'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=200),
        ),
    ]
