# Generated by Django 5.0 on 2024-01-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_alter_invoice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
    ]
