# Generated by Django 5.0 on 2024-01-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_remove_invoice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_note',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
