# Generated by Django 5.0 on 2024-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_alter_invoice_client_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_image',
            field=models.ImageField(blank=True, default='invoice.png', null=True, upload_to='invoice_image/'),
        ),
    ]
