# Generated by Django 5.0 on 2024-01-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_invoice_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GHC', 'GHC'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN')], max_length=200),
        ),
    ]
