# Generated by Django 5.0 on 2024-01-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_alter_invoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GHS', 'GHS'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN')], max_length=200),
        ),
    ]
