# Generated by Django 5.0 on 2024-02-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_remove_invoice_item_title_remove_invoice_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_title',
            new_name='title',
        ),
    ]
