# Generated by Django 5.0 on 2024-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0037_rename_item_title_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
