# Generated by Django 5.0 on 2024-02-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0042_pagerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageRequest',
        ),
    ]
