# Generated by Django 5.0 on 2024-02-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0044_alter_invoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD 🇺🇸', 'USD 🇺🇸'), ('GHS 🇬🇭', 'GHS 🇬🇭'), ('GBP 🇬🇧', 'GBP 🇬🇧'), ('EUR 🇪🇺', 'EUR 🇪🇺'), ('NGN 🇳🇬', 'NGN 🇳🇬')], max_length=200),
        ),
    ]
